on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Install homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install pcre
        run: brew install pcre
      - name: Checkout project
        uses: actions/checkout@v3.0.0
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Build MIR
        run: cd mir && make && cd ..
      - name: Setup nightly Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - name: Run tests
        run: BUZZ_PATH=./dist zig build -Duse_mimalloc=false && BUZZ_PATH=./dist zig build test -Duse_mimalloc=false
      - name: Run tests JIT
        run: BUZZ_PATH=./dist zig build -Djit -Duse_mimalloc=false && BUZZ_PATH=./dist zig build test -Djit -Duse_mimalloc=false
      - name: Run tests JIT always on
        run: BUZZ_PATH=./dist zig build -Djit -Djit_debug_on -Duse_mimalloc=false && BUZZ_PATH=./dist zig build test -Djit -Djit_debug_on -Duse_mimalloc=false
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3.0.0
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Build MIR
        run: cd mir && make && cd ..
      - name: Setup nightly Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - name: Run tests
        run: BUZZ_PATH=./dist zig build -Duse_mimalloc=false && BUZZ_PATH=./dist zig build test -Duse_mimalloc=false
      - name: Run tests JIT
        run: BUZZ_PATH=./dist zig build -Djit -Duse_mimalloc=false && BUZZ_PATH=./dist zig build test -Djit -Duse_mimalloc=false
      - name: Run tests JIT always on
        run: BUZZ_PATH=./dist zig build -Djit -Djit_debug_on -Duse_mimalloc=false && BUZZ_PATH=./dist zig build test -Djit -Djit_debug_on -Duse_mimalloc=false
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - name: Setup nightly Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig fmt --check src/*.zig src/**/*.zig
